kubectl delete -f files/02-basic-cluster.yaml
kubectl delete -f files/02-basic-cluster.yaml
kubectl delete -f files/manual-zookeeper.yaml
kubectl delete -f files/kafka-operator.yaml
kubectl delete statefulset test-cluster-1
kubectl delete service test-cluster-1
kubectl delete service test-cluster-1-broker-0
kubectl delete service test-cluster-1-broker-1
kubectl delete service test-cluster-1-broker-2